# Generated by Django 3.0.5 on 2020-04-24 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('category', models.CharField(choices=[('fiction', 'Adult Fiction'), ('nonfiction', 'Adult Non-Fiction'), ('children', "Children's Books")], max_length=64)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('vote_points', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('creator_user', models.ForeignKey(help_text='User who created this reading list', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingListVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ReadingList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readinglist',
            name='votes',
            field=models.ManyToManyField(related_name='reading_lists_voted_on', through='core.ReadingListVote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('isbn', models.CharField(blank=True, max_length=127, null=True)),
                ('author', models.CharField(blank=True, max_length=127, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=127, null=True)),
                ('reading_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ReadingList')),
            ],
        ),
    ]
