# Generated by Django 3.0.5 on 2020-04-22 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='users_who_voted',
            field=models.ManyToManyField(related_name='reading_lists_voted_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
